# =======================================
# Networks
# =======================================
networks:
  traefik:
    external: true
  internal:
    driver: bridge

services:
# =======================================
# Traefik
# =======================================
  traefik:
    image: traefik:v3.0
    container_name: traefik
    command:
      - --api.dashboard=true
      - --api.insecure=false
    ports:
      - "80:80"
      - "443:443"
      - "8082:8082"  # prometheus metrics
    volumes:
      - /run/user/1000/docker.sock:/var/run/docker.sock:ro
      - ./traefik/dynamic:/etc/traefik/dynamic:ro
      - ./traefik/traefik.yml:/traefik.yml:ro
      - ./traefik/acme.json:/acme.json
    networks:
      - traefik
    restart: unless-stopped
    labels:
#      - traefik.http.routers.http-catch.rule=HostRegexp(`{any:.+}`)
#      - traefik.http.routers.http-catch.entrypoints=web
#      - traefik.http.routers.http-catch.middlewares=redirect@file

#      - traefik.http.routers.traefik.rule=Host(`kh.octopod.eu`)
#      - traefik.http.routers.traefik.entrypoints=websecure
#      - traefik.http.routers.traefik.tls.certresolver=letsencrypt
#      - traefik.http.routers.traefik.service=api@internal
#      - traefik.http.routers.traefik.middlewares=authelia@file


      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traf.octopod.eu`)
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.tls.certresolver=letsencrypt
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.middlewares=authelia@docker
      - traefik.http.services.traefik.loadbalancer.server.port=8080

# =======================================
# Pometheus
# =======================================
  prometheus:
    image: prom/prometheus:latest
    container_name: traef-prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.size=256MB'
    ports:
      - 9090:9090
    labels:
      - "traefik.http.routers.prometheus.rule=Host(`prom.octopod.eu`)"
      - "traefik.http.routers.prometheus.service=prometheus"
      - "traefik.http.routers.prometheus.middlewares=traefik-auth"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
    networks:
      - traefik
      - internal
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"
# =======================================
# Grafana
# =======================================
  grafana:
    image: grafana/grafana:latest
    container_name: traef-grafana
    environment:
      - GF_PATHS_PLUGINS=${GF_PATHS_PLUGINS}
    #   - GF_INSTALL_PLUGINS=${GF_INSTALL_PLUGINS}
    ports:
      - "3000:3000"
    volumes:
    #   - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/plugins:/var/lib/grafana/plugins
      - grafana-data:/var/lib/grafana
    networks:
      - traefik
      - internal
    labels:
      - "traefik.http.routers.grafana.rule=Host(`graf.octopod.eu`)"
      - "traefik.http.middlewares.grafana.redirectscheme.port=3000"
      - "traefik.http.routers.grafana.entrypoints=web"


# =======================================
# Authelia
# =======================================
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    volumes:
      - ./authelia/configuration.yml:/config/configuration.yml:ro
      - ./authelia/users_database.yml:/config/users_database.yml:ro
      - authelia-data:/config/data
    networks:
      - traefik
      - internal
    environment:
      - AUTHELIA_JWT_SECRET=${AUTHELIA_JWT_SECRET}
      - AUTHELIA_SESSION_SECRET=${AUTHELIA_SESSION_SECRET}
      - AUTHELIA_STORAGE_ENCRYPTION_KEY=${AUTHELIA_STORAGE_KEY}
    restart: unless-stopped
    depends_on:
      - redis
    labels:
      - traefik.enable=true
      - traefik.http.routers.authelia.rule=Host(`authl.octopod.eu`)
      - traefik.http.routers.authelia.entrypoints=websecure
      - traefik.http.routers.authelia.tls.certresolver=letsencrypt
      - traefik.http.services.authelia.loadbalancer.server.port=9091
      - traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://authl.octopod.eu/
      - traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true
      - traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email

# =======================================
# Redis
# =======================================
  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - internal
    volumes:
      - redis-data:/data
    restart: unless-stopped

# =======================================
# Dashy
# =======================================
  dashy:
    image: lissy93/dashy:latest
    container_name: dashy
    volumes:
      - ./dashy/conf.yml:/app/user-data/conf.yml
#      - ./dashy:/app/public/item-icons:ro
#      - ./dashy/conf.yml:/conf.yml:rw
    networks:
      - traefik
    restart: unless-stopped
#    environment:
      # Принуждаваме Dashy да използва нашия конфигурационен файл
#      - DASHY_CONFIG_PATH=/app/public/conf.yml
    labels:
      - traefik.enable=true
      - traefik.http.routers.dashy.rule=Host(`dash.octopod.eu`)
      - traefik.http.routers.dashy.entrypoints=websecure
      - traefik.http.routers.dashy.tls.certresolver=letsencrypt
      - traefik.http.routers.dashy.middlewares=authelia@docker
      - traefik.http.services.dashy.loadbalancer.server.port=8080


# =======================================
# Fenrus Dashboard
# =======================================
  fenrus:
    image: revenz/fenrus:latest
    container_name: fenrus
    volumes:
      - ./fenrus-data:/app/data
    environment:
      - FENRUS_OIDC_AUTH_URL=https://auth.octopod.eu/application/o/authorize/
      - FENRUS_OIDC_TOKEN_URL=https://auth.octopod.eu/application/o/token/
      - FENRUS_OIDC_CLIENT_ID=fenrus
      - FENRUS_OIDC_CLIENT_SECRET=${FENRUS_OIDC_CLIENT_SECRET}
      - FENRUS_OIDC_SCOPE=openid profile email
      - FENRUS_OIDC_LOGOUT_URL=https://auth.octopod.eu/application/o/logout/
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.fenrus.rule=Host(`fenrus.octopod.eu`)
      - traefik.http.routers.fenrus.entrypoints=websecure
      - traefik.http.routers.fenrus.tls.certresolver=letsencrypt
#      - traefik.http.routers.fenrus.middlewares=authentik@docker
      - traefik.http.services.fenrus.loadbalancer.server.port=3000
      - traefik.http.routers.fenrus.middlewares=authentik-forwardauth@file

# =======================================
# Authentik SSO
# =======================================
  authentik-server:
    image: ghcr.io/goauthentik/server:2024.6.1
    container_name: authentik-server
#    command: ["manage.py", "server"]
    environment:
      AUTHENTIK_SECRET_KEY: "${AUTHENTIK_SECRET_KEY}"
      AUTHENTIK_POSTGRESQL__HOST: authentik-db
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: "${AUTHENTIK_DB_PASSWORD}"
      AUTHENTIK_POSTGRESQL__DATABASE: authentik
#      AUTHENTIK_EMAIL__HOST: "${AUTHENTIK_EMAIL__HOST}"
#      AUTHENTIK_EMAIL__PORT: "${AUTHENTIK_EMAIL__PORT}"
#      AUTHENTIK_EMAIL__USERNAME: "${AUTHENTIK_EMAIL__USERNAME}"
#      AUTHENTIK_EMAIL__PASSWORD: "${AUTHENTIK_EMAIL__PASSWORD}"
#      AUTHENTIK_EMAIL__FROM: "${AUTHENTIK_EMAIL__FROM}"
      #AUTHENTIK_EMAIL__USE_TLS=true
      # Use SSL
#      #AUTHENTIK_EMAIL__USE_SSL=false
      AUTHENTIK_EMAIL__TIMEOUT: 10
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_REDIS__PORT: 6379
    depends_on:
      - authentik-db
      - redis
    volumes:
      - ./authentik-data:/data
    ports:
      - "9100:9000"
    networks:
      - traefik
      - internal
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.authentik.rule=Host(`auth.octopod.eu`)
      - traefik.http.routers.authentik.entrypoints=websecure
      - traefik.http.routers.authentik.tls.certresolver=letsencrypt
      - traefik.http.services.authentik.loadbalancer.server.port=9000

# =======================================
# Authentik DB - Postgres
# =======================================
  authentik-db:
    image: postgres:15
    container_name: authentik-db
    environment:
      POSTGRES_USER: authentik
      POSTGRES_PASSWORD: "${AUTHENTIK_DB_PASSWORD}"
      POSTGRES_DB: authentik
    volumes:
      - ./authentik-db:/var/lib/postgresql/data
    networks:
      - internal
    restart: unless-stopped

# =======================================
# Ping healthcheck service (optional, can be a simple busybox container that pings 10.10.30.1)
# =======================================
  pingcheck:
    image: busybox
    container_name: pingcheck
    command: /bin/sh -c "while true; do ping -c1 10.10.30.1 >/dev/null 2>&1 && echo ok || echo nok; sleep 30; done"
    networks:
      - internal
    restart: unless-stopped

# =======================================
# Volumes
# =======================================
volumes:
  redis-data:
  authelia-data:
  prometheus-data:
  grafana-data:
