entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
  metrics:
    address: :8082 

#metrics:
#  prometheus: 
#    entryPoint: metrics
#    buckets:
#      - 0.100000
#      - 0.300000
#      - 1.200000
#      - 5.000000
#    addEntryPointsLabels: true
#    addServicesLabels: true


providers:
  docker:
    network: traefik 
    ## dolnia red e ot staria config
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: /etc/traefik/dynamic
    watch: true


certificatesResolvers:
  letsencrypt:
    acme:
      email: it@octopod.eu
      storage: /acme.json
      httpChallenge:
        entryPoint: web

http:
  routers:
    metrics:
      rule: "Host(`metrics.octopod.eu`)"
      entrypoints: "web"

  services:
    metrics:
      loadbalancer:
        server:
          port: "8082"



api:
  dashboard: true

log:
  level: INFO
accessLog: {}
