http:
  middlewares:
    authentik-forwardauth:
      forwardAuth:
        address: "https://auth.octopod.eu/outpost.goauthentik.io/auth/traefik"
        trustForwardHeader: true
        authResponseHeaders:
          - X-authentik-username
          - X-authentik-groups
