# Home Assistant External Service Configuration
# Date: 2025-07-11
# Author: kirily67

http:
  routers:
    homeassistant:
      rule: "Host(`ha.octopod.eu`)"
      entryPoints:
        - websecure
      service: homeassistant
      # No auth middleware needed - HA handles auth via OIDC
      #middlewares:
      #  - homeassistant-auth
      tls:
        certResolver: letsencrypt

    # HTTP to HTTPS redirect
    homeassistant-http:
      rule: "Host(`ha.octopod.eu`)"
      entryPoints:
        - web
      middlewares:
        - redirect-to-https
      service: homeassistant

  services:
    homeassistant:
      loadBalancer:
        servers:
          - url: "http://10.11.12.8:8123"  # Replace with your HA VM IP
        healthCheck:
          path: /
          interval: 30s
          timeout: 10s

  middlewares:
#    homeassistant-auth:
#      forwardAuth:
#        address: "http://authelia:9091/api/verify?rd=https://auth.octopod.eu/"
#        trustForwardHeader: true
#        authResponseHeaders:
#          - Remote-User
#          - Remote-Groups
#          - Remote-Name
#          - Remote-Email

    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true
