version: '3.8'

networks:
  traefik:
    external: true
  internal:
    driver: overlay

services:
  traefik:
    image: traefik:v3.0
    command:
      - --api.dashboard=true
      - --api.insecure=false
      - --providers.docker=true
      - --providers.docker.swarmMode=false
      - --providers.docker.network=traefik
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.letsencrypt.acme.email=kirily67@example.com
      - --certificatesresolvers.letsencrypt.acme.storage=/acme.json
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
      - --log.level=INFO
      - --accesslog=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-acme:/acme.json
    networks:
      - traefik
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.traefik.rule=Host(`traf.octopod.eu`)
        - traefik.http.routers.traefik.entrypoints=websecure
        - traefik.http.routers.traefik.tls.certresolver=letsencrypt
        - traefik.http.routers.traefik.service=api@internal
        - traefik.http.routers.traefik.middlewares=authelia@docker
        - traefik.http.services.traefik.loadbalancer.server.port=8080

  authelia:
    image: authelia/authelia:latest
    volumes:
      - ./authelia:/config:ro
    networks:
      - traefik
      - internal
    environment:
      - AUTHELIA_JWT_SECRET_FILE=/run/secrets/authelia_jwt_secret
      - AUTHELIA_SESSION_SECRET_FILE=/run/secrets/authelia_session_secret
      - AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE=/run/secrets/authelia_storage_key
    secrets:
      - authelia_jwt_secret
      - authelia_session_secret
      - authelia_storage_key
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.authelia.rule=Host(`auth.octopod.eu`)
        - traefik.http.routers.authelia.entrypoints=websecure
        - traefik.http.routers.authelia.tls.certresolver=letsencrypt
        - traefik.http.services.authelia.loadbalancer.server.port=9091
        - traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://auth.yourdomain.com/
        - traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true
        - traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email

  redis:
    image: redis:alpine
    networks:
      - internal
    volumes:
      - redis-data:/data
    deploy:
      replicas: 1

  dashy:
    image: lissy93/dashy:latest
    volumes:
      - ./dashy/conf.yml:/app/public/conf.yml:ro
    networks:
      - traefik
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.dashy.rule=Host(`dash.octopod.eu`)
        - traefik.http.routers.dashy.entrypoints=websecure
        - traefik.http.routers.dashy.tls.certresolver=letsencrypt
        - traefik.http.routers.dashy.middlewares=authelia@docker
        - traefik.http.services.dashy.loadbalancer.server.port=80

volumes:
  traefik-acme:
  redis-data:

secrets:
  authelia_jwt_secret:
    external: true
  authelia_session_secret:
    external: true
  authelia_storage_key:
    external: true
